version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb3
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  C:\Users\Rewan ElAttar\Desktop:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
