version: '3'
services:
  mysqldb3:
    image: "mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_PASSWORD=root
     - MYSQL_DATABASE=test
    ports:
      - "3307:3307"

  app:
    image: app
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb3:3307/test?autoReconnect=true&useSSL=false
      spring.datasource.username: "root"
      spring.datasource.password: "root"

    build:
      context: "./"
      dockerfile: "Dockerfile"

    depends_on:
      - mysqldb3


